### ISSUE TITLE
Spelling mistakes in en_gb.json

### ISSUE THREAD

**Issue by thisisthedogtor** [MMK21Hub/Capitalisation-Fixes#7]
"subtitles.entity.horse.armor" needs to be spelled "Horse Armour equips"
"createWorld.customize.buffet.title" needs to be spelled "Buffet World Customisation"

**Comment by MMK21Hub** [comment]
Thanks for pointing that out! I must have overlooked those strings, since I tend to just paste my changes from `en_us` into `en_gb`.

Good news: the new build tool (#6) modifies existing translation strings instead of replacing them, which means that the correct British English spellings get preserved.

I've just released [version 2.6](https://github.com/MMK21Hub/Capitalisation-Fixes/releases/tag/v2.6) of the pack, which has been built by the build tool, so it includes these corrections.

Thank you again for taking the time to report the mistakes :)
